### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'AnnotationSet' and 'AnnotationSet'

### ISSUE THREAD

**Issue by ruckc** [laclouis5/globox#24]
**Describe the bug**
When trying to combine multiple AnnotationSet objects, get unsupported operand type '+'.

**To Reproduce**
```python
coco1 = AnnotationSet.from_coco("coco-1/annotations/instances_default.json")
coco2 = AnnotationSet.from_coco("coco-2/annotations/instances_default.json")
coco = coco1+coco2
```

**Expected behavior**
Per the documentation, I expected the ability of combining AnnotationSet objects.

**Environment (please complete the following information):**
 - Ubuntu 22.04
 - Python 3.10.6
 - Globox 2.1.0

**Additional context**
I believe we need to add an `__add__` method to support AnnotationSet concatenation.

**Comment by laclouis5** [comment]
Hi,

This is a documentation error, I modified this operator from `+` to `|` a while ago because it matches more closely the semantics: its a union (in the mathematical sense) rather than a concatenation. The `|` operator is used for Python dictionaries and set so I believe this API is cleaner since `AnnotationSet` behaves like a set as its name suggests.

Could you try that `|` works for you, i.e. `coco = coco1 | coco2`? I'll update the wrong documentation, thanks for the report.

**Comment by ruckc** [comment]
Yes, that works.  Now I just need to figure out how to programmatically deal with duplicate IDs that are unique images.

**Comment by laclouis5** [comment]
It depends how you define "unique" images. Normally an image identity is defined by its `id` so you should not have two ID's for the same image/annotation. You could post-process the result of the union and remove duplicate images.
